"""Claim-level hybrid generation with strict provenance boundaries.

This phase intentionally uses a small, deterministic decomposition step.  It
only activates for an explicit source clause followed by an explicit request
for explanation.  Each clause is generated by its own isolated path and the
merge is a typed data operation, never a free-form LLM rewrite.
"""
from __future__ import annotations

import re
from dataclasses import asdict, dataclass
from typing import Any

from .general import GeneralAssistant, GeneralGenerator
from .generator import GroundedGenerator, GroundedRAGAssistant
from .response import GroundedAnswer, ResolvedSource


@dataclass(frozen=True, slots=True)
class HybridSegment:
    text: str
    source_type: str  # retrieved | ai_generated
    citation_handles: list[str]
    support_status: str  # supported | inference | unsupported

    def __post_init__(self) -> None:
        if self.source_type not in {"retrieved", "ai_generated"}:
            raise ValueError("unsupported hybrid source_type")
        if self.source_type == "ai_generated" and self.citation_handles:
            raise ValueError("ai_generated segments cannot contain citations")
        if self.source_type == "retrieved" and self.support_status == "supported" and not self.citation_handles:
            raise ValueError("supported retrieved segments require citations")


@dataclass(frozen=True, slots=True)
class HybridAnswer:
    original_query: str
    answer: str
    answer_mode: str
    provenance: str
    segments: list[HybridSegment]
    citations: list[str]
    resolved_sources: list[ResolvedSource]
    provider: str
    model: str
    generation_latency_seconds: float
    input_tokens: int | None
    output_tokens: int | None
    total_tokens: int | None
    disclaimer: str | None = None
    validation_status: str = "validated"

    def __post_init__(self) -> None:
        if self.answer_mode not in {"hybrid", "insufficient_evidence"}:
            raise ValueError("invalid hybrid answer mode")
        if self.answer_mode == "hybrid" and self.provenance != "mixed":
            raise ValueError("hybrid answers must use mixed provenance")
        if self.answer_mode == "insufficient_evidence" and self.citations:
            raise ValueError("insufficient evidence cannot expose citations")
        validate_hybrid_segments(self.segments)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def validate_hybrid_segments(segments: list[HybridSegment]) -> None:
    """Fail closed on citation/source-type mixing at the final boundary."""

    for segment in segments:
        if segment.source_type == "ai_generated" and segment.citation_handles:
            raise ValueError("AI-generated segment cannot carry citations")
        if segment.source_type == "retrieved" and segment.support_status == "supported" and not segment.citation_handles:
            raise ValueError("retrieved supported segment lacks citations")


_EN_SPLIT = re.compile(r"\s+(?:and|then)\s+(?=(?:explain|tell\s+me|why|how|what\s+does)\b)", re.IGNORECASE)
_AR_SPLIT = re.compile(r"\s+(?:و|ثم)\s*(?=(?:اشرح|وضح|لماذا|ليه|ما\s+معنى|ازاي)\b)", re.IGNORECASE)


def split_hybrid_query(query: str) -> tuple[str, str] | None:
    """Split only explicit source+explanation forms; otherwise return None."""

    for pattern in (_EN_SPLIT, _AR_SPLIT):
        match = pattern.search(query)
        if match:
            source = query[: match.start()].strip(" ,;؟?")
            general = query[match.end() :].strip(" ,;؟?")
            if source and general:
                return source, general
    return None


class HybridAssistant:
    """Run grounded and general generators independently, then type-merge."""

    def __init__(
        self,
        *,
        grounded: GroundedRAGAssistant | None = None,
        general: GeneralAssistant | None = None,
        grounded_generator: GroundedGenerator | None = None,
        general_generator: GeneralGenerator | None = None,
    ) -> None:
        self._grounded = grounded or GroundedRAGAssistant(generator=grounded_generator)
        self._general = general or GeneralAssistant(generator=general_generator)

    def answer(self, query: str) -> HybridAnswer:
        parts = split_hybrid_query(query)
        if not parts:
            raise ValueError("query is not an explicit hybrid source/explanation request")
        source_query, general_query = parts
        grounded = self._grounded.answer(source_query)
        if grounded.no_answer:
            segment = HybridSegment(grounded.answer, "retrieved", [], "unsupported")
            return HybridAnswer(
                query,
                grounded.answer,
                "insufficient_evidence",
                "retrieved",
                [segment],
                [],
                [],
                grounded.provider,
                grounded.model,
                grounded.generation_latency_seconds,
                grounded.input_tokens,
                grounded.output_tokens,
                grounded.total_tokens,
            )

        general = self._general.answer(general_query)
        retrieved_segment = HybridSegment(grounded.answer, "retrieved", list(grounded.citations), "supported")
        general_segment = HybridSegment(general.answer, "ai_generated", [], "inference")
        return HybridAnswer(
            query,
            f"{grounded.answer}\n\n{general.answer}",
            "hybrid",
            "mixed",
            [retrieved_segment, general_segment],
            list(grounded.citations),
            list(grounded.resolved_sources),
            f"{grounded.provider}+{general.provider}",
            f"{grounded.model}+{general.model}",
            grounded.generation_latency_seconds + general.generation_latency_seconds,
            _sum_tokens(grounded.input_tokens, general.input_tokens),
            _sum_tokens(grounded.output_tokens, general.output_tokens),
            _sum_tokens(grounded.total_tokens, general.total_tokens),
        )


def _sum_tokens(first: int | None, second: int | None) -> int | None:
    return first + second if first is not None and second is not None else None
